version: "3"

services:
  app:
    container_name: projects
    build: .
    restart: always
    depends_on:
      - db
      - minio
    ports:
      - ${CONTAINER_PORT:-8080}:${HOST_PORT:-8080}
    command: ["--host", "0.0.0.0","--port","8080"]
    environment:
      - MYSQL_DB_HOST=mysql
      - MYSQL_DB_NAME=platiagro
      - MYSQL_DB_USER=root
      - MYSQL_DB_PASSWORD=
      - MINIO_ENDPOINT=minio-service:9000
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_REGION_NAME=us-east-1
      - JUPYTER_ENDPOINT=http://jupyter:8888

  db:
    container_name: "${DB_HOST:-mysql}"
    image: mysql:8.0.3
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:${DB_PORT:-3306}
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-platiagro}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  minio:
    container_name: "${MINIO_HOST:-minio-service}"
    image: minio/minio
    volumes:
      - ./data-minio:/var/lib/minio
    ports:
      - "${MINIO_PORT:-9000}:9000"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER:-minio}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-minio123}"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3

  jupyter:
    container_name: "${JUPYTER_HOST:-jupyter}"
    image: jupyter/base-notebook
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
